export const GET_USERS = "GET_USERS";
export const UPDATE_USER = "UPDATE_USER";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const CREATE_USER = "CREATE_USER";
export const DROP_USER = "DROP_USER";
export const SET_IMPERSONATION_USER = "SET_IMPERSONATION_USER";
export const UPDATE_USER_STATUS = "UPDATE_USER_STATUS";
