development:
  adapter: postgresql
  encoding: unicode
  database: ifusion_lite_development
  pool: 5
  username: postgres
  password: 'd1231'

test:
  adapter: postgresql
  encoding: unicode
  database: ifusion_lite_test
  pool: 5
  username: postgres
  password: 'd1231'